### PR TITLE
sign function as builInFunction

### PR DESCRIPTION
**Pull request by alexeyegorov**
Sign function as described here (http://en.wikipedia.org/wiki/Sign_function) is easy to implement, but can be a nice-to-have builtinFunction for exp4j.
Great library!

### CODE REVIEW

**Comment by fasseg** [comment]
Hey @alexeyegorov , 

Thanks for the input, this might indeed be a useful feature. I will have a look at it, and come back to you.

**Comment by alexeyegorov** [comment]
That'll be great. It is furthermore exciting how easy you've made exp4j to
be extended! :)
I was not actually able to build the project without errors. It does
compile, but while installing it outputs following test errors:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.objecthunter.exp4j.ArrayStackTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.112 sec
Running net.objecthunter.exp4j.ExpressionBuilderTest
Tests run: 201, Failures: 0, Errors: 134, Skipped: 0, Time elapsed: 0.461
sec <<< FAILURE!
Running net.objecthunter.exp4j.ExpressionTest
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<<
FAILURE!
Running net.objecthunter.exp4j.ExpressionValidateTest
Tests run: 23, Failures: 0, Errors: 18, Skipped: 0, Time elapsed: 0.003 sec
<<< FAILURE!
Running net.objecthunter.exp4j.FunctionsTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec
Running net.objecthunter.exp4j.PerformanceTest
+------------------------+---------------------------+--------------------------+
| Implementation         | Calculations per Second   | Percentage of Math
    |
+------------------------+---------------------------+--------------------------+
| Java Math              |                4195222,50 |
100,00 % |
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.006 sec
<<< FAILURE!
Running net.objecthunter.exp4j.shuntingyard.ShuntingYardTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec
Running net.objecthunter.exp4j.tokenizer.TokenizerTest
Tests run: 22, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.013 sec
<<< FAILURE!

Results :

Tests in error:
  testExpressionBuilder01(net.objecthunter.exp4j.ExpressionBuilderTest)
  testExpressionBuilder02(net.objecthunter.exp4j.ExpressionBuilderTest):
Could not initialize class net.objecthunter.exp4j.function.Functions
  testExpressionBuilder03(net.objecthunter.exp4j.ExpressionBuilderTest):
Could not initialize class net.objecthunter.exp4j.function.Functions
...


Not sure what is going wrong.

Cheers,
Alexey

2015-04-22 15:32 GMT+02:00 frank asseg <notifications@github.com>:

**Comment by alexeyegorov** [comment]
Now tests run through. But I still get some error concerning Javadoc. I'm not that familiar with that stuff and maybe you can help me with this too:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project exp4j: MavenReportException: Error while creating archive: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```

**Comment by sarxos** [comment]
Disabling ```javadoc``` generation by adding ```-Dmaven.javadoc.skip=true``` should be enough, however, in one of the next steps it will ask you to provide ```gpg``` key passphrase, so you should come up with another fancy switch which is ```-Dgpg.skip=true```. Finally your command should look like the following:

```plain
 mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true
```

**Comment by alexeyegorov** [comment]
Thx @sarxos as I'm newbie in the maven world. it would cost me some more hours figuring out.... ;)
From this point it builds successfully. Hope there aren't any other mistakes and sgn function will be in the next update!

**Comment by alexeyegorov** [comment]
@leogtzr you're right! Braces are added!

**Comment by fasseg** [comment]
Will merge this for the next release iteration

**Pull request merged**
