### PR TITLE
Adding support for numerical constants. (Feature request) issue #32

### PR DESCRIPTION
**Pull request by leogtzr**

### CODE REVIEW

**Comment by stkent** [comment]
Nice idea, I was just going to add this myself.

**Comment by sarxos** [comment]
This is very nice idea :)

**Comment by alexeyegorov** [comment]
must-have! I'm adding those constants manually, but in case of automatic expression evaluation it just blows up the code! Hope to see it soon in the lib.

**Comment by fasseg** [comment]
Will merge this for next release iteration

**Comment by fasseg** [comment]
Merged function into master

**Pull request closed without merging**
